/* jshint unused: true, esversion: 6 */
const { parse } = require('bibtex-parse');
const { readdirSync, readFileSync, writeFileSync } = require('fs');

const prop = (e, prop) => e.properties[prop] ? e.properties[prop].value : null;

const strval = (str = '') => (str || '').replace(/\W/g, '').toLowerCase();

const hash = e => ({
	authorTitle: strval((prop(e, 'author') || 'none').match(/([^\s]+)\s*(,|and |et |$)/)[1]) + ':' + // surname (comes before comma or 'and')
        strval(prop(e, 'title', '')).slice(0, 50),
    doi: prop(e, 'doi') ? strval(prop(e, 'doi')) : null,
    abstract: prop(e, 'abstract') ? strval(prop(e, 'abstract')).slice(0, 100) : null
});

const same = (e1, e2) => e1.similarityHash.doi && e1.similarityHash.doi === e2.similarityHash.doi ||
                         e1.similarityHash.abstract && e1.similarityHash.abstract === e2.similarityHash.abstract ||
                         e1.similarityHash.authorTitle === e2.similarityHash.authorTitle;

const serialize = entries => {
	return entries
		.sort((a, b) => a.hash < b.hash ? -1 : a.hash > b.hash ? 1 : 0)
		.map(entry => {
			let props = Object.keys(entry.properties)
				.map(k => {
					let v = entry.properties[k],
						val = String(v.value).replace(/\s+/g, ' '),
						braced = v.brace === 'curly' ? `{${val}}` : v.brace === 'quote' ? `"${val}"` : val;
					return `  ${k.padEnd(14)}= ${braced}`;
				});
			return `@${entry.type.toLowerCase()}{${entry.id},\n${props.join(',\n')}\n}`;
		})
		.join('\n');
};

const databases = readdirSync('databases').map(f => f.replace(/\.bib$/, ''));
const exclusionReasons = readdirSync('exclusions').map(f => f.replace(/\.bib$/, ''));
const entries = [];
const exclusions = [];

exclusionReasons.forEach(reason => {
	parse(readFileSync(`exclusions/${reason}.bib`, 'utf8')).entries.forEach(e => {
		e.similarityHash = hash(e);
		e.reason = reason;
		exclusions.push(e);
	});
});

console.log('Loading databases...');
databases.forEach(database => {
	let dbentries = [];
	parse(readFileSync(`databases/${database}.bib`, 'utf8')).entries.forEach(e => {
		e.similarityHash = hash(e);
		if (!dbentries.find(e_ => same(e, e_))) { dbentries.push(e); }
	});
	dbentries.forEach(e => {
		e.id = e.similarityHash.authorTitle.split(':')[0] + prop(e, 'year');
		e.properties.database = { value: database, brace: 'curly' };
		e.duplicate = entries.find(e_ => same(e, e_));
		e.exclude = exclusions.find(e_ => same(e, e_));
		if (e.exclude) { e.exclude.used = true; }
		if (e.duplicate) {
			e.duplicate.properties.database.value += `, ${database}`;
			Object.keys(e.properties).forEach(k => {
				if (!e.duplicate.properties[k]) { e.duplicate.properties[k] = e.properties[k]; }
			});
		}
		entries.push(e);
	});
	console.log(`${database.padStart(30)}: ${dbentries.length}`);
});

let withoutDupes = entries.filter(e => !e.duplicate),
	eligible = withoutDupes.filter(e => !e.exclude);

console.log('Total'.padStart(30) + `: ${entries.length}`);
console.log('');
console.log('Removing duplicates...');
console.log('duplicates'.padStart(30) + `: (${entries.length - withoutDupes.length})`);
console.log('Total'.padStart(30) + `: ${withoutDupes.length}`);
console.log('');

console.log('Applying exclusions...');
exclusionReasons.forEach(reason => {
	let ineligible = withoutDupes.filter(e => e.exclude && e.exclude.reason === reason);
	console.log(reason.padStart(30) + `: (${ineligible.length})`);
});
console.log('TOTAL ELIGIBLE'.padStart(30) + `: ${eligible.length} (${withoutDupes.length} - ${withoutDupes.length - eligible.length})`);

let header = '% Results generated by bibtex-exclude\n';
writeFileSync('results.bib', header + serialize(eligible), 'utf8');
console.log('Results written to results.bib');

/*const unusedExclusions = exclusions.filter(e => !e.used);
writeFileSync('unused-exclusions.bib', serialize(unusedExclusions), 'utf8');
exclusionReasons.forEach(name => {
	const usedExclusions = exclusions.filter(e => e.reason === name && e.used);
	writeFileSync(`exclusions/${name}.bib`, serialize(usedExclusions), 'utf8');
});
*/